# Generated by Django 5.2.4 on 2025-08-01 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunosmodel',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='alunosmodel',
            name='mae_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alunosmodel',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alunosmodel',
            name='pai_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alunosmodel',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alunosmodel',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alunosmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='EscolaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=100)),
                ('data_matricula', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escola', to='alunos.alunosmodel')),
            ],
        ),
    ]
