# Generated by Django 5.2.4 on 2025-08-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alunosmodel_cpf_alunosmodel_mae_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunosmodel',
            name='estado_do_aluno',
            field=models.CharField(choices=[('Ativo', 'ATIVO'), ('Inativo', 'INATIVO')], default='Ativo', max_length=10),
        ),
        migrations.AddField(
            model_name='alunosmodel',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'MASCULINO'), ('Feminino', 'FEMININO')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='escolamodel',
            name='ano',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
