# Generated by Django 5.2.4 on 2025-08-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_alunosmodel_estado_do_aluno_alunosmodel_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolamodel',
            name='ano',
            field=models.IntegerField(null=True),
        ),
    ]
