# Generated by Django 5.2.4 on 2025-08-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_escolamodel_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunosmodel',
            name='estado_do_aluno',
        ),
        migrations.AddField(
            model_name='alunosmodel',
            name='ano',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alunosmodel',
            name='data_matricula',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alunosmodel',
            name='serie',
            field=models.CharField(choices=[('1° ano', '1º Ano'), ('2° ano', '2º Ano'), ('3° ano', '3º Ano'), ('4° ano', '4º Ano'), ('5° ano', '5º Ano'), ('6° ano', '6º Ano'), ('7° ano', '7º Ano'), ('8° ano', '8º Ano'), ('9° ano', '9º Ano'), ('1° ANO Ensino Médio', '1º Ano Ensino Médio'), ('2° ANO Ensino Médio', '2º Ano Ensino Médio'), ('3° ANO Ensino Médio', '3º Ano Ensino Médio')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alunosmodel',
            name='telefone_mae',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alunosmodel',
            name='telefone_pai',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alunosmodel',
            name='turno',
            field=models.CharField(choices=[('Manhã', 'MANHÃ'), ('Tarde', 'TARDE'), ('Noite', 'NOITE')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alunosmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alunosmodel',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'MASCULINO'), ('Feminino', 'FEMININO')], max_length=10),
        ),
        migrations.DeleteModel(
            name='EscolaModel',
        ),
    ]
