# Generated by Django 5.2.4 on 2025-08-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_remove_alunosmodel_estado_do_aluno_alunosmodel_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunosmodel',
            name='turno',
            field=models.CharField(choices=[('MANHÃ', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10, null=True),
        ),
    ]
