# Generated by Django 5.2.4 on 2025-08-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_alter_alunosmodel_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunosmodel',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='alunosmodel',
            name='serie',
            field=models.CharField(choices=[('1° ANO', '1º Ano'), ('2° ANO', '2º Ano'), ('3° ANO', '3º Ano'), ('4° ANO', '4º Ano'), ('5° ANO', '5º Ano'), ('6° ANO', '6º Ano'), ('7° ANO', '7º Ano'), ('8° ANO', '8º Ano'), ('9° ANO', '9º Ano'), ('1° ANO Ensino Médio', '1º Ano Ensino Médio'), ('2° ANO Ensino Médio', '2º Ano Ensino Médio'), ('3° ANO Ensino Médio', '3º Ano Ensino Médio')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alunosmodel',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=10),
        ),
    ]
