# Generated by Django 5.2.4 on 2025-08-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_alter_alunosmodel_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunosmodel',
            name='ano',
        ),
        migrations.AddField(
            model_name='alunosmodel',
            name='foto_aluno',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_alunos/'),
        ),
    ]
