# Generated by Django 5.2.4 on 2025-08-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_remove_alunosmodel_ano_alunosmodel_foto_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunosmodel',
            name='idade',
            field=models.IntegerField(null=True),
        ),
    ]
