# Generated by Django 5.2.4 on 2025-08-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0009_alunosmodel_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunosmodel',
            name='cpf',
            field=models.CharField(blank=True, help_text='Apenas 11 dígitos', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='alunosmodel',
            name='rg',
            field=models.CharField(blank=True, help_text='Apenas números', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alunosmodel',
            name='telefone_mae',
            field=models.CharField(blank=True, help_text='Apenas números', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alunosmodel',
            name='telefone_pai',
            field=models.CharField(blank=True, help_text='Apenas números', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alunosmodel',
            name='telefone_responsavel',
            field=models.CharField(blank=True, help_text='Apenas números', max_length=20, null=True),
        ),
    ]
